swagger: '2.0'
info:
  title: 'Todo Service'
  description: 'API to manage todo activity'
  version: '1.0.0'
  license:
    name: 'GPL-3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
host: 'localhost'
tags:
  - name: 'Task'
    description: 'Endpoint untuk mengedit Task'
schemes:
  - 'http'
paths:
  /add:
    post:
      tags:
        - 'Task'
      operationId: 'addTask'
      description: 'Untuk menambahkan job baru'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: body
          name: body
          description: input task
          required: true
          schema:
            properties:
              job:
                type: string
                example: makan geprek
              assignee_id:
                type: number
                example: 1
              attachment:
                type: string
                example: 1612867757630-580.bin
      responses:
        '200':
          description: task yang baru di input
          schema:
            $ref: '#/definitions/Task'
        '400':
          description: 'data pekerjaan tidak valid'
        '500':
          description: 'kesalahan server'
  /list:
    get:
      operationId: 'listTask'
      description: mengembalikan daftar task
      tags:
        - 'Task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      # summary: Gets all users
      responses:
        '200':
          description: daftar task
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
        '500':
          description: kesalahan server
  /done:
    put:
      operationId: 'doneTask'
      description: merubah status 'done' ke selesai (true)
      tags:
        - 'Task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: task
          schema:
            $ref: '#/definitions/Task'
  /cancel:
    put:
      operationId: 'doneTask'
      description: merubah status 'cancel' ke selesai (true)
      tags:
        - 'Task'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
        - 'text/plain'
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: task
          schema:
            $ref: '#/definitions/Task'
            

definitions:
  Task:
    type: object
    properties:
      id:
        type: number
        description: id task
      job:
        type: string
        description: nama pekerjaan / tugas
      done:
        type: boolean
        description: status progress pekerjaan 
      cancelled:
        type: boolean
        description: status pembatalan pekerjaan
      attachment:
        type: string
        description: file tambahan dari pekerjaan
        example: 1612867757630-580.bin
      added_at:
        type: date
        description: tanggal saat pekerjaan dibuat
        example: 2021-02-09 17:49:18.09079
      assigneeId:
        $ref: '#/definitions/Worker'
  Worker:
    type: object
    properties:
      id:
        type: number
        description: identifier pekerja
        example: 1
      name:
        type: string
        description: nama pekerja
        example: risky
      age:
        type: number
        description: umur pekerja
        example: 50
      bio:
        type: string
        description: deskripsi pekerja
        example: web developer
      address:
        type: string
        description: alamat pekerja
        example: jl. sanbercode no. 5
      photo:
        type: string
        description: file foto pekerja
        example: 1612861039515-181.bin
  